// Copyright (c) 2023, Mikhail Kirillov <mikkirillov@yandex.ru>

package runes

const (
	ASYMP    rune = '≈'
	CENT     rune = '¢'
	COPY     rune = '©'
	DEG      rune = '°'
	DIVIDE   rune = '÷'
	DOLLAR   rune = '$'
	EURO     rune = '€'
	FDASH    rune = '‒'
	FNOF     rune = 'ƒ'
	FRAC12   rune = '½'
	FRAC14   rune = '¼'
	FRAC34   rune = '¾'
	GE       rune = '≥'
	GRAVE    rune = '`'
	HELLIP   rune = '…'
	INFIN    rune = '∞'
	INT      rune = '∫'
	LAQUO    rune = '«'
	LE       rune = '≤'
	MACR     rune = '¯'
	MDASH    rune = '—'
	MICRO    rune = 'µ'
	MIDDOT   rune = '·'
	NBHYPHEN rune = '‑'
	NDASH    rune = '–'
	NE       rune = '≠'
	NLDR     rune = '‥'
	NOT      rune = '¬'
	ORDF     rune = 'ª'
	ORDM     rune = 'º'
	PAR      rune = '∥'
	PERP     rune = '⊥'
	PLUSMN   rune = '±'
	POUND    rune = '£'
	RAQUO    rune = '»'
	REG      rune = '®'
	SECT     rune = '§'
	SIM      rune = '∼'
	SUM      rune = '∑'
	SUP1     rune = '¹'
	SUP2     rune = '²'
	SUP3     rune = '³'
	TIMES    rune = '×'
	TRADE    rune = '™'
	UML      rune = '¨'
	YEN      rune = '¥'
	ZWSP     rune = '\u200B'
	ZWNBSP   rune = '\uFEFF'
	ZWJ      rune = '\u200D'
	ZWNJ     rune = '\u200C'
)
